import {aiResults} from "./data";import type {AIPromptResult} from "./types";
export interface EvaluationParams{modelName:string;prompt:string;context:string;language:string;ipId:string}
export interface ParsedAIResponse{mentioned:boolean;rank:number|null;summary:string;reason:string;sentiment:number;accuracy:number;sources:number;issues:string[]}
export async function runAIPromptEvaluation(params:EvaluationParams):Promise<AIPromptResult>{const provider=params.modelName.toLowerCase();const hasKey=provider.includes("gemini")?Boolean(process.env.GEMINI_API_KEY):provider.includes("perplexity")?Boolean(process.env.PERPLEXITY_API_KEY):Boolean(process.env.OPENAI_API_KEY);if(!hasKey){const sample=aiResults.find(x=>x.modelName===params.modelName&&x.context===params.context)||aiResults[0];return{...sample,id:`sample-${Date.now()}`,prompt:params.prompt,language:params.language}}
// MVP adapter boundary: production implementations call each provider's official API here.
// Deliberately returns a safe sample until provider-specific request/response contracts are enabled.
const sample=aiResults.find(x=>x.modelName===params.modelName)||aiResults[0];return{...sample,id:`adapter-${Date.now()}`,prompt:params.prompt};}
export function parseAIResponse(response:unknown):ParsedAIResponse{if(typeof response!=="object"||response===null)throw new Error("Invalid AI response");const r=response as Partial<ParsedAIResponse>;return{mentioned:Boolean(r.mentioned),rank:typeof r.rank==="number"?r.rank:null,summary:String(r.summary||""),reason:String(r.reason||""),sentiment:Number(r.sentiment||50),accuracy:Number(r.accuracy||50),sources:Number(r.sources||50),issues:Array.isArray(r.issues)?r.issues.map(String):[]}}
export function calculatePromptResult(parsed:ParsedAIResponse,params:EvaluationParams):AIPromptResult{return{id:`ai-${Date.now()}`,ipId:params.ipId,modelName:params.modelName,prompt:params.prompt,context:params.context,language:params.language,mentioned:parsed.mentioned,recommendationRank:parsed.rank,responseSummary:parsed.summary,recommendationReason:parsed.reason,nonRecommendationReason:parsed.mentioned?"":"推薦根拠不足",sentimentScore:parsed.sentiment,contextFitScore:parsed.mentioned?75:40,accuracyScore:parsed.accuracy,sourceQualityScore:parsed.sources,competitorGapScore:parsed.mentioned?35:75,detectedIssues:parsed.issues,createdAt:new Date().toISOString()}}
