import Papa from "papaparse";import type {AIPromptResult,SNSSignal} from "./types";
export type CSVType="ai"|"sns";export interface CSVError{row:number;messages:string[]}
const aiRequired=["id","ipId","modelName","prompt","context","language","mentioned","sentimentScore","contextFitScore","accuracyScore","sourceQualityScore","competitorGapScore","createdAt"];
const snsRequired=["id","ipId","platform","keyword","hashtag","postVolume","engagementCount","engagementRate","sentimentScore","fanContext","language","region","createdAt"];
const numeric={ai:["recommendationRank","sentimentScore","contextFitScore","accuracyScore","sourceQualityScore","competitorGapScore"],sns:["postVolume","engagementCount","engagementRate","sentimentScore"]};
export function validateCSV(text:string,type:CSVType){const parsed=Papa.parse<Record<string,string>>(text,{header:true,skipEmptyLines:true});const required=type==="ai"?aiRequired:snsRequired;const headers=parsed.meta.fields||[];const missing=required.filter(x=>!headers.includes(x));if(missing.length)return{valid:[],errors:[{row:1,messages:[`不足ヘッダー: ${missing.join(", ")}`]}]};const valid:Record<string,unknown>[]=[],errors:CSVError[]=[];parsed.data.forEach((row,i)=>{const messages:string[]=[];required.forEach(k=>{if(row[k]===undefined||row[k]==="")messages.push(`${k} は必須です`)});numeric[type].forEach(k=>{if(row[k]!==""&&row[k]!==undefined&&Number.isNaN(Number(row[k])))messages.push(`${k} は数値で指定してください`)});if(messages.length)errors.push({row:i+2,messages});else valid.push(normalizeRow(row,type))});return{valid,errors};}
function normalizeRow(row:Record<string,string>,type:CSVType){const out:Record<string,unknown>={...row};numeric[type].forEach(k=>{if(row[k]!==""&&row[k]!==undefined)out[k]=Number(row[k])});if(type==="ai"){out.mentioned=row.mentioned==="true";out.recommendationRank=row.recommendationRank?Number(row.recommendationRank):null;out.detectedIssues=parseArray(row.detectedIssues)}else out.samplePosts=parseArray(row.samplePosts);return out;}
const parseArray=(s?:string)=>{if(!s)return[];try{const v=JSON.parse(s);return Array.isArray(v)?v:[s]}catch{return s.split("|").map(x=>x.trim())}};
export function toCSV(data:(AIPromptResult|SNSSignal|Record<string,unknown>)[]){return Papa.unparse(data.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,Array.isArray(v)?JSON.stringify(v):v]))),{newline:"\r\n"})}
